### ISSUE TITLE
bug - remove last item from list

### ISSUE THREAD

**Issue by ltdeta** [fyneworks/multifile#15]
if you remove the last item from list the MultiFile object will also removed
after that adding new items to the list , it doesn't work anymore

on the demo-page you can test it
- add one item to the list
- push upload-button -> one element
- add another item to the list
- push upload button -> empty

**Comment by ltdeta** [comment]
Update: 
i found the problem
for example initialised element `imf`
```js
 $('#imf').MultiFile({
    max: 3, 
    accept: 'gif|jpg|png'
  });
```
append new files to the list 
```html
<input name="imf[]" class="button MultiFile-applied MultiFile" id="imf" submitName="imf[]" style="position: absolute; width: 90px; top: -3000px;" type="file" ...>
<input name="imf[]" class="button MultiFile-applied MultiFile" id="imf_F1" submitName="imf[]" style="position: absolute; width: 90px; top: -3000px;" type="file" ...>
<input name="imf[]" class="button MultiFile-applied MultiFile" id="imf_F2" submitName="imf[]" style="width: 90px; " type="file" ...>
```
reset the list with
```js
 $('#imf').MultiFile('reset');
```
and now
```html
<input name="imf[]" class="button MultiFile-applied MultiFile" id="imf_F2" submitName="imf[]" style="width: 90px;" type="file" ...>
```
the element `imf_F2` is visible (active) but element `imf` was initialized

i made a quick workaround for me and now it works :)
=> after removing all elements changing the element id from last insert element to the initialised one

**Comment by fyneworks** [comment]
This has to be the case (as far as I know) because the browsers (for security reasons) don't allow javascript to set the value of a file element. Once you select a file on the first input element. 

I propose a different approach in v2.2 (0b5580294e354bd70142d80a3bca98fc56d82359) so that the original ID is always available, but it involves applying it to the wrapper div (which is never removed). That way all api calls continue to work on the same id originally used to start the plugin, in your case `$('imf').MultiFile('size')`, etc...

There is an alternative perhaps.... which would be to only ever remove the clones, but if an attempt is made to remove the first file selected the plugin could remove the last clone (the element currently visible), clear the value of the original element and bring it back into view. I could write that in v2.3 if there's a demand for it.

**Comment by ltdeta** [comment]
The approach in v2.2 is a good solution
