### ISSUE TITLE
Removing commas(,) or wrap the commans

### ISSUE THREAD

**Issue by dvinodeluru** [fyneworks/multifile#39]
Thanks for the file control can you please help me to remove the (,) commas or hide them, can't execute or manipulative with DOM that fails the file upload feature. Im using Angular js to save data

Thanks in advance

**Comment by fyneworks** [comment]
Hey there! 

Can you provide a sample of your code? The commas only appear in the labels, they shouldn't impact form submission.

**Comment by jildertmiedema** [comment]
This happens to me too
When i use the browser multi select option it add commas and one remove button.
When i add per file it does not show the comma and a remove button for both each file.
So i think it has to do with the `<input multiple>` option

**Comment by fyneworks** [comment]
I think I understand what you mean and that is something that will not change in this plugin.

The browser security settings prohibits scripts from manipulating the contents of a file input element.

When you select 5 files at once, the plugin cannot remove 1, it must remove them all. That's why they appear as a single choice and there is only 1 remove button.

There are other solutions out there that handle this different (they bypass the <input type="file"/> element altogether. But I think this is (for now) beyond of the scope of this project.,
