### ISSUE TITLE
Delete button should display on select of multiple files instead of comma serpate

### ISSUE THREAD

**Issue by kishorwalke** [fyneworks/multifile#48]
If user select multiple files at the same time. It need to display separately with delete icon instead if comma sepration. like it is displaying for single file seletion.

**Comment by mctinetti** [comment]
I'm looking also for this Feaure!

**Comment by digggggggggg** [comment]
That's not possible thru Javascript because the browser does not allow you to manipulate the value of the selection. Files selected together have to stay together with this file input approach, according to the html5 spec. 

But there are other plugin that use a different approach that will deliver the functionality you need

**Comment by emilsgulbis** [comment]
@digggggggggg Please name of that other plugin, that deliver this functionality without ajax submitting, like this plugin does.

**Comment by fyneworks** [comment]
As far as we know that cannot be done with Javascript, period. As @digggggggggg said above, the browser does not provide a way to manipulate the selection of multiple files that were selected together. 

Happy to be corrected if we missed anything. 

But maybe you shud try something like this... https://blueimp.github.io/jQuery-File-Upload/
